---
abstract: 'Test Pod for invalid HTTP/S links'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Cwd: '0'
  FindBin: '0'
  Test::Builder::Tester: '0'
  Test::Fatal: '0'
  Test::MockModule: '0'
  Test::More: '0.88'
  Test::TempDir::Tiny: '0'
  autodie: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Pod-Links
no_index:
  directory:
    - corpus
    - t
    - xt
provides:
  Test::Pod::Links:
    file: lib/Test/Pod/Links.pm
    version: '0.001'
requires:
  Carp: '0'
  HTTP::Tiny: '0.014'
  Pod::Simple::SimpleTree: '0'
  Scalar::Util: '0'
  Test::Builder: '0'
  Test::Pod: '0'
  URI: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Test-Pod-Links/issues
  homepage: https://github.com/skirmess/Test-Pod-Links
  repository: https://github.com/skirmess/Test-Pod-Links.git
version: '0.001'
x_serialization_backend: 'YAML::Tiny version 1.70'
