---
abstract: 'test Pod for invalid HTTP/S links'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  File::Temp: '0'
  FindBin: '0'
  Test::Builder::Tester: '0'
  Test::Fatal: '0'
  Test::MockModule: '0'
  Test::More: '0.88'
  constant: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla, CPAN::Meta::Converter'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Pod-Links
no_index:
  directory:
    - corpus
    - t
    - xt
requires:
  Carp: '0'
  HTTP::Tiny: '0.014'
  Pod::Simple::Search: '0'
  Pod::Simple::SimpleTree: '0'
  Scalar::Util: '0'
  Test::Builder: '0'
  Test::XTFiles: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Test-Pod-Links/issues
  homepage: https://github.com/skirmess/Test-Pod-Links
  repository: https://github.com/skirmess/Test-Pod-Links.git
version: '0.003'
x_spdx_expression: BSD-2-Clause-FreeBSD
